### ISSUE TITLE
[QUESTION] - tuifeed now as a pkgsrc package

### ISSUE THREAD

**Issue by 0323pin** [veeso/tuifeed#1]
Not really a question, more FYI. I've packaged and merged `tuifeed` into pkgsrc main branch, https://mail-index.netbsd.org/pkgsrc-changes/2021/11/16/msg243429.html

`tuifeed` will become available to NetBSD users using the native package manager within a few days.

Regards,
pin@NetBSD.org

**Comment by veeso** [comment]
That sounds great, thank you very much!

**Comment by veeso** [comment]
Added NetBSD installation on install script

**Comment by 0323pin** [comment]
Thanks!

**Comment by 0323pin** [comment]
@veeso 
Hi,
Would you mind giving some info on the status of this project?
Thanks!

**Comment by veeso** [comment]
Hi, I'm currently working on 0.2.0 version after a long time since the last update.
I'm going to introduce some suggested features and fix some bugs.
Expect an update in the next few days.

**Comment by 0323pin** [comment]
Awesome, thanks. I'll keep an eye on it.

> I'm going to introduce some suggested features

Any chance one of these is my request, https://github.com/veeso/tuifeed/issues/5
