### ISSUE TITLE
Implement dates

### ISSUE THREAD

**Issue by 0323pin** [veeso/tuifeed#5]
Hi,

NetBSD package maintainer here. I'm currently using `neix` for feeds from project I maintain packages for.
`neix` is no longer maintained and I would like to move to `tuifeed`, also because I could drop `ncursesw` from my system doing so.

There's a feature that stops me from doing that. `neix` displays dates, which is rather useful info for a package maintainer.
See [screenshot](https://i.postimg.cc/c0Hsw-8df/2022-02-18-172046-1366x768-scrot.png) 

Would this be something that could be implemented? And, are you willing to do so?

**Comment by veeso** [comment]
I will add a parameter in the configuration to do that

**Comment by 0323pin** [comment]
@veeso Thank you for the new release!
Dates work fine for projects hosted at sourcehut from where feeds are provided in `rss.xml` format.

![2022-08-07-051652_1366x768_scrot](https://user-images.githubusercontent.com/90570748/183273648-8c90ff3c-02dd-495b-833e-73e38439cfae.png)

But, fail to display for github hosted projects, as github uses the `atom` format for the feeds.

![2022-08-07-051709_1366x768_scrot](https://user-images.githubusercontent.com/90570748/183273675-65a496cb-8ac4-499d-90e8-022f68144a25.png)

Any chance to get these too?

Btw, I've updated the package and should be able to merge the update later today, latest tomorrow.

**Comment by 0323pin** [comment]
@veeso Can this be extended to include also atom?

```
impl From<RssEntry> for Article {
    fn from(entry: RssEntry) -> Self {
        let content_or_summary = content_or_summary(&entry);
        Self {
            title: entry
                .title
                .map(|x| str_helpers::strip_html(x.content.as_str())),
            authors: entry.authors.into_iter().map(|x| x.name).collect(),
            summary: content_or_summary,
            url: entry
                .links
                .get(0)
                .map(|x| x.href.clone())
                .unwrap_or(entry.id),
            date: entry.published.map(DateTime::<Local>::from),
        }
    }
}
```

**Comment by veeso** [comment]
Can you provide me with the link you're getting the feed from?

**Comment by 0323pin** [comment]
@veeso Any github repository really but, as an example we can take `tuifeed` itself, https://github.com/veeso/tuifeed/releases.atom

**Comment by veeso** [comment]
Ok, I'll make a fix to use `updated` in case `published` is not available

**Comment by 0323pin** [comment]
Thank you!
Let me know if you need testing before release. I'm happy to do local test builds from git-HEAD if you like.

**Comment by 0323pin** [comment]
Fixed by https://github.com/veeso/tuifeed/pull/9

**Comment by veeso** [comment]
0.2.1 will be released today
