### ISSUE TITLE
It can't load DigiTimes' feed

### ISSUE THREAD

**Issue by ealib** [veeso/tuifeed#6]
## Description

tuifeed fails to load DigiTimes news feed

## Steps to reproduce

Add `https://www.digitimes.com/rss/daily.xml` feed and run *tuifeed*

```ini
"DIGITIMES" = "https://www.digitimes.com/rss/daily.xml"
```

## Expected behaviour

Load the feed and list feed contents.

## Error shown

tuifeed show the following error

```
Could not fetch feed "DIGITIMES": HTTP request failed: https://www.digitimes.com/rss/daily.xml: Connection Failed: An existing
connection was forcibly closed by the remote host. (os error 10054)
```

## Environment

- OS: Windows 10 x64
- Architecture x86_64
- Rust version: ?
- tuifeed version: 0.1.0

**Comment by veeso** [comment]
The reason is related to the TLS protocols used by the website, which are incompatible with rustls. Unfortunately this is not working even when switching go `native-tls`, so there's nothing I can do.
